name: Even Odd Checker

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number"
        required: true
        default: "10"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Program
        env:
          NUMBER: ${{ github.event.inputs.number }}
        run: |
          python app.py
